# Generated by Django 5.0.14 on 2026-07-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_item', models.CharField(max_length=50, unique=True)),
                ('nome_item', models.CharField(max_length=200)),
                ('quantidade_atual', models.PositiveIntegerField(default=0)),
                ('tipo', models.CharField(choices=[('Escritório', 'Escritório'), ('Copa', 'Copa'), ('TI', 'TI'), ('Geral', 'Geral'), ('Temporário', 'Temporário')], max_length=20)),
                ('requer_aprovacao', models.BooleanField(default=False, help_text='Se marcado, saídas/empréstimos deste item ficam Pendentes até aprovação (regra do charl para itens de TI).')),
            ],
            options={
                'ordering': ['nome_item'],
            },
        ),
    ]
