# Generated by Django 5.0.14 on 2026-07-30 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaboradores', '0001_initial'),
        ('itens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('tipo_movimento', models.CharField(choices=[('Saída', 'Saída'), ('Empréstimo', 'Empréstimo'), ('Devolução', 'Devolução')], max_length=20)),
                ('status_ti', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Rejeitado', 'Rejeitado'), ('Concluído', 'Concluído')], default='Aprovado', max_length=20)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='colaboradores.colaborador')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='itens.item')),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
