# Generated by Django 5.0.14 on 2026-07-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('setor', models.CharField(blank=True, max_length=120)),
                ('matricula', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
